version: '3.8'

services:
  server:
    image: yohimaa/recepie_book_app:server
    ports:
      - '5000:5000'
    volumes:
      - ./server/database.sqlite:/app/database.sqlite
    environment:
      - NODE_ENV=production
      - PORT=5000
    restart: unless-stopped

  client:
    image: yohimaa/recepie_book_app:client
    ports:
      - '5500:80'
    depends_on:
      - server
    restart: unless-stopped
